language: php

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - gv-1

php:
  - 5.3
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
